version: '3'
services:
  crawler:
    container_name: crawler-api
    restart: always
    build: ./crawler
    ports:
      - '8000:8000'
  analytics:
    container_name: twitter-analytics
    restart: always
    build: ./twitter-analytics
    ports:
      - '8080:8080'
  admin:
    container_name: admin-dashboard
    restart: always
    build: ./admin
    ports:
      - '5000:5000'

